security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin5pass"
ssl.keystore.location=./kafka-1.keystore.jks
ssl.keystore.password=unit5pass
ssl.key.password=unit5pass
ssl.truststore.location=./kafka-1.truststore.jks
ssl.truststore.password=unit5pass
ssl.endpoint.identification.algorithm=
