KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    user_admin="admin5pass"
    user_ui="ui5pass"
    user_producer="producer5pass"
    user_consumer="consumer5pass";
};

Client {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin5pass";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin5pass";
};

